// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNMui3iR7FWz0tlMz2hARrQqj6PfzUjVc',
    appId: '1:1096722861505:web:4a9b3f4075117f0eaff340',
    messagingSenderId: '1096722861505',
    projectId: 'simple-soc-app',
    authDomain: 'simple-soc-app.firebaseapp.com',
    storageBucket: 'simple-soc-app.appspot.com',
    measurementId: 'G-VF8JE2VSP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhO-mLI_wlqnr-40TCHQ0DtyGtcEo17iY',
    appId: '1:1096722861505:android:7278ae6b3e545369aff340',
    messagingSenderId: '1096722861505',
    projectId: 'simple-soc-app',
    storageBucket: 'simple-soc-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzZQNDBgv0DX4gDkXOc9-OziXPGB8lkbE',
    appId: '1:1096722861505:ios:2d91844ca29cd182aff340',
    messagingSenderId: '1096722861505',
    projectId: 'simple-soc-app',
    storageBucket: 'simple-soc-app.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzZQNDBgv0DX4gDkXOc9-OziXPGB8lkbE',
    appId: '1:1096722861505:ios:0b880fd19bd854c1aff340',
    messagingSenderId: '1096722861505',
    projectId: 'simple-soc-app',
    storageBucket: 'simple-soc-app.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
